### PR TITLE
Use fixed alpine image; Add certificates to access https endpoints

### LINKED ISSUE #3: Error if vault is using SSL
I get this error when using https for vault.

```
time="2018-04-25T20:17:30Z" level=fatal msg="Get https://vault.domain.com/v1/sys/mounts: x509: failed to load system roots and no roots provided" 
```

If i use internal vault (which also has ssl) I get wrong certificated as i should, but there is no option to skip it.

I've also built it, it didn't complain about ssh as i had the ca-certificates on pod, but i got and endless loop. 

I will debug more and open a new issue if i figure out the problem, but it's most likely related to the mount paths.

### PR DESCRIPTION
**Pull request by sfrique**
Use alpine 3.7 instead of latest and fixes #3 

Hope that helps.

### CODE REVIEW

**Comment by sfrique** [comment]
@sunshinekitty any updates?

**Comment by sunshinekitty** [comment]
Sorry, I missed your issue and this PR.  I'll get a new tagged image up to dockerhub with these fixes.  I do plan to updating docs/errors to make mount paths better understood.

**Comment by sfrique** [comment]
No problem!
Thanks for merging it, once the image is built, i will use it as my main image.

You may also point the docs to that comment on the issue where I described a bit about the mount paths until the docs are not updated. 

Great project!

**Comment by sunshinekitty** [comment]
@sfrique this is now pushed up at sunshinekitty/vaultingkube:v0.1.1

**Comment by sfrique** [comment]
Thank you!

**Pull request merged**
